// 阶段定义
var PHASES = {
  PROJECT_PREP:     { label: '项目准备与整合',  color: '#3B82F6', bg: '#EFF6FF' },
  MOCK_INTERVIEW_1: { label: '第一次模拟面试',  color: '#EF4444', bg: '#FEF2F2' },
  JAVA_SE:          { label: 'Java SE',         color: '#10B981', bg: '#ECFDF5' },
  JVM:              { label: 'JVM',             color: '#8B5CF6', bg: '#F5F3FF' },
  JUC:              { label: 'JUC',             color: '#F97316', bg: '#FFF7ED' },
  MOCK_INTERVIEW_2: { label: '第二次模拟面试',  color: '#EF4444', bg: '#FEF2F2' },
  SPRING:           { label: 'Spring',          color: '#06B6D4', bg: '#ECFEFF' },
  MQ_NETWORK_NETTY: { label: 'MQ/网络/Netty',   color: '#F59E0B', bg: '#FFFBEB' },
  MICROSERVICE:     { label: '微服务/分布式',    color: '#6366F1', bg: '#EEF2FF' },
  MOCK_INTERVIEW_3: { label: '第三次模拟面试',  color: '#EF4444', bg: '#FEF2F2' },
  SYSTEM_DESIGN:    { label: '系统设计',        color: '#78716C', bg: '#F5F5F4' },
  MOCK_INTERVIEW_4: { label: '第四次模拟面试',  color: '#EF4444', bg: '#FEF2F2' }
};

// 71天计划数据
var PLAN_DATA = [
  { date:'2026-03-01', phase:'PROJECT_PREP', title:'统一目标与架构边界', morning:'明确"AI增强电商平台"范围，确定 Java 主链路与 Python AI 子服务边界', afternoon:'画系统总架构图（网关、商城服务、缓存、MQ、AI服务、DB）', evening:'整理技术选型理由（为什么这样拆）', output:'架构图 v1 + 边界说明' },
  { date:'2026-03-02', phase:'PROJECT_PREP', title:'工程骨架与基础设施', morning:'搭建 Java 商城工程骨架（模块划分、配置、日志）', afternoon:'搭建 AI 子服务工程骨架（RAG 接口、健康检查）', evening:'统一代码规范与接口规范', output:'项目目录结构 + API 契约草案' },
  { date:'2026-03-03', phase:'PROJECT_PREP', title:'商城核心域建模', morning:'完成用户/商品/购物车领域建模', afternoon:'完成核心表结构与索引初版', evening:'补充实体关系和业务流程图', output:'ER 图 + 领域模型图' },
  { date:'2026-03-04', phase:'PROJECT_PREP', title:'交易主链路打通（上）', morning:'商品查询、购物车、下单接口打通', afternoon:'库存预扣、订单创建流程跑通', evening:'联调并记录异常路径', output:'下单时序图 v1' },
  { date:'2026-03-05', phase:'PROJECT_PREP', title:'交易主链路打通（下）', morning:'支付回调、订单状态流转、补偿逻辑', afternoon:'事务边界与幂等处理（防重下单/重复回调）', evening:'补齐关键单元测试', output:'订单状态机 + 幂等策略文档' },
  { date:'2026-03-06', phase:'PROJECT_PREP', title:'RAG 服务化接入', morning:'定义检索接口（召回/重排/答案生成）', afternoon:'Java 调用链接入（超时、重试、熔断、降级）', evening:'验证 AI 不可用时主链路可降级', output:'AI 调用链路图 + 降级策略' },
  { date:'2026-03-07', phase:'PROJECT_PREP', title:'多智能体能力接入商城', morning:'接入导购/问答/推荐 Agent', afternoon:'工具调用、上下文管理、Prompt 模板治理', evening:'整理 3 个业务场景（导购、售后、商品咨询）', output:'场景映射文档 + Demo 清单' },
  { date:'2026-03-08', phase:'PROJECT_PREP', title:'缓存与异步化', morning:'接入 Redis 缓存（热点商品、详情页）', afternoon:'接入 MQ 异步链路（下单后异步任务）', evening:'梳理一致性风险点', output:'缓存策略 + MQ 流程图' },
  { date:'2026-03-09', phase:'PROJECT_PREP', title:'稳定性机制', morning:'限流、隔离、熔断、降级策略补齐', afternoon:'重试与死信处理策略', evening:'整理高可用设计说明', output:'稳定性策略清单' },
  { date:'2026-03-10', phase:'PROJECT_PREP', title:'可观测性建设', morning:'统一日志规范（traceId/spanId）', afternoon:'指标采集（RT、QPS、错误率）与链路追踪', evening:'准备排障看板', output:'可观测性最小闭环文档' },
  { date:'2026-03-11', phase:'PROJECT_PREP', title:'性能压测（第一轮）', morning:'压测下单、查询、AI问答三条链路', afternoon:'定位瓶颈（慢SQL、线程池、缓存命中）', evening:'制定优化清单', output:'压测报告 v1（基线）' },
  { date:'2026-03-12', phase:'PROJECT_PREP', title:'性能优化（第一轮）', morning:'缓存优化、索引优化、连接池参数优化', afternoon:'线程池与批处理策略调整', evening:'回归验证', output:'压测报告 v2（前后对比）' },
  { date:'2026-03-13', phase:'PROJECT_PREP', title:'故障演练与复盘', morning:'演练超时雪崩/重复消费/缓存不一致场景', afternoon:'按"发现-定位-修复-验证"闭环复盘', evening:'沉淀标准故障话术', output:'故障复盘文档（2-3个案例）' },
  { date:'2026-03-14', phase:'PROJECT_PREP', title:'项目面试化封装', morning:'整理简历项目描述（职责、难点、结果量化）', afternoon:'准备 20+ 项目深挖问答', evening:'演练 3-5 分钟项目介绍', output:'项目面试 QA v1 + 项目介绍稿' },
  { date:'2026-03-15', phase:'MOCK_INTERVIEW_1', title:'项目一面模拟 + 复盘', morning:'项目一面（50分钟）：背景、架构、难点、优化、追问', afternoon:'逐题复盘，补齐"答不顺"的问题', evening:'重录项目讲解（控制 5 分钟）', output:'项目模拟复盘 v1' },
  { date:'2026-03-16', phase:'MOCK_INTERVIEW_1', title:'项目二面模拟 + 拷打', morning:'项目二面（50分钟）：重点拷打稳定性、数据一致性、性能指标', afternoon:'补齐量化数据与故障案例表达', evening:'形成项目终版话术', output:'项目模拟复盘 v2 + 项目终版话术' },
  { date:'2026-03-17', phase:'JAVA_SE', title:'语言基础与对象模型', morning:'视频：尚硅谷 2025 Java 面试题（包装类/String/equals/hashCode/final/static）', afternoon:'文档整理：JavaSE 大厂面试知识清单 + 面试题总览，补齐易混淆点和反例', evening:'模拟面试：30 题快问快答，重点拷打 String、equals/hashCode、自动装箱陷阱', output:'Java 基础易错清单 + 10 题标准答案' },
  { date:'2026-03-18', phase:'JAVA_SE', title:'集合源码（List）', morning:'视频：黑马集合基础课 + 尚硅谷面试题（集合总览与 List）', afternoon:'文档整理：集合框架体系 + Collection + ArrayList，对照整理复杂度和典型场景', evening:'模拟面试：List 模块 15 题 + 手写简化 ArrayList（扩容+迭代器）', output:'List 体系对比图 + 手写 ArrayList 代码' },
  { date:'2026-03-19', phase:'JAVA_SE', title:'集合源码（Map）', morning:'视频：黑马 Java 集合源码课（HashMap put/resize/treeify 核心章节）', afternoon:'文档整理：HashMap 源码文档，整理 put 流程、扩容、树化', evening:'模拟面试：HashMap 高频拷打 + 手写 LRU', output:'HashMap 流程图 + LRU 手写代码' },
  { date:'2026-03-20', phase:'JAVA_SE', title:'异常与IO/NIO', morning:'视频：尚硅谷 2025 Java 面试题（异常、IO/NIO 相关章节）', afternoon:'文档整理：异常体系、BIO/NIO/AIO、Selector 机制；补充排查话术', evening:'模拟面试：异常与 IO 高频题口述 + 手写 NIO 简易服务端', output:'IO 模型对比表 + 异常排查 checklist' },
  { date:'2026-03-21', phase:'JAVA_SE', title:'泛型/反射/动态代理', morning:'视频：尚硅谷 2025 Java 面试题（泛型、反射、动态代理章节）', afternoon:'文档整理：类型擦除/桥接方法/PECS/JDK代理 vs CGLIB 一页纸对照', evening:'模拟面试：反射与代理拷打 + 手写简易 IOC（最小可用）', output:'代理机制对比表 + IOC demo' },
  { date:'2026-03-22', phase:'JAVA_SE', title:'Java 新特性', morning:'视频：黑马集合框架课（JDK8 新特性）+ 尚硅谷 Lambda/Stream 章节', afternoon:'文档整理：Java 8-21 常考点（Lambda/Stream/Optional/CompletableFuture/虚拟线程）', evening:'模拟面试：新特性高频题口述（重点可落地场景）', output:'JavaSE 一页纸手册（新特性版）' },
  { date:'2026-03-23', phase:'JAVA_SE', title:'JavaSE 综合复盘', morning:'视频：回看前 6 天未吃透视频片段（优先集合和并发集合）', afternoon:'文档整理：统一收口到 3 份文档：集合总图、HashMap/CHM 对照、JavaSE 高频问答清单', evening:'模拟面试：JavaSE 全模块模拟（50 分钟）+ 复盘（70 分钟）', output:'JavaSE 模块定稿 + 弱项清单 v1' },
  { date:'2026-03-24', phase:'JVM', title:'内存结构与对象创建', morning:'视频：宋红康 JVM（内存结构、对象创建、对象头相关章节）', afternoon:'文档整理：JVM 面试题 + JavaGuide 内存区域文档，整理运行时数据区、对象创建、TLAB', evening:'模拟面试：内存结构与对象创建拷打（至少 10 题）+ 白板画 JVM 内存图', output:'内存结构图 + 对象创建口述稿' },
  { date:'2026-03-25', phase:'JVM', title:'GC 理论与算法', morning:'视频：宋红康 JVM（GC Roots、可达性分析、引用类型、回收算法章节）', afternoon:'文档整理：JavaGuide GC 文档，整理可达性分析/四种引用/三大算法/分代思想', evening:'模拟面试：GC 理论高频题口述（10-15 题）+ 算法对比图复画', output:'GC 算法对比图 + 四种引用对比表' },
  { date:'2026-03-26', phase:'JVM', title:'GC 收集器', morning:'视频：宋红康 JVM（Serial/Parallel/CMS/G1/ZGC 章节）', afternoon:'文档整理：结合 JVM 面试题整理 CMS vs G1、触发条件、参数与选型', evening:'模拟面试：收集器拷打（CMS 缺点、G1 Mixed GC、FullGC 触发）+ 画流程图', output:'收集器对比表 + CMS/G1 流程图' },
  { date:'2026-03-27', phase:'JVM', title:'类加载机制', morning:'视频：宋红康 JVM（类加载、双亲委派、类加载器章节）', afternoon:'文档整理：加载->验证->准备->解析->初始化全链路；补 SPI/Tomcat 打破双亲委派案例', evening:'模拟面试：类加载机制追问 + 手写简易类加载器', output:'类加载流程图 + 双亲委派口述稿' },
  { date:'2026-03-28', phase:'JVM', title:'JVM 调优实战', morning:'视频：尚硅谷 2025 面试题 JVM 调优章节 + Arthas 文档 walkthrough', afternoon:'文档整理：按"症状->命令->定位->修复"整理 OOM/CPU飙高/频繁 FullGC 三类案例', evening:'模拟面试：调优实战拷打（线上故障追问）+ 排障话术演练', output:'调优案例库 + 标准排障话术' },
  { date:'2026-03-29', phase:'JVM', title:'JIT/直接内存/性能点', morning:'视频：宋红康 JVM（JIT、逃逸分析、直接内存相关章节）', afternoon:'文档整理：结合极客时间专栏整理 JIT 分层编译、逃逸分析、直接内存关键点', evening:'模拟面试：JVM 加分题口述（JIT/逃逸/直接内存）+ 薄弱点补齐', output:'JVM 加分点笔记 + 高频追问清单' },
  { date:'2026-03-30', phase:'JVM', title:'JVM 综合复盘', morning:'视频：回看本周漏掉或不熟的 JVM 片段（优先 GC/调优）', afternoon:'文档整理：统一收口到 3 份文档：JVM 结构图册、调优案例库、JVM 高频问答', evening:'模拟面试：JVM 全模块模拟（50 分钟）+ 复盘（70 分钟）', output:'JVM 模块定稿 + 弱项清单 v1' },
  { date:'2026-03-31', phase:'JUC', title:'JMM 与 volatile', morning:'视频：黑马并发实战（JMM/volatile 可见性与有序性）', afternoon:'指令重排与内存屏障', evening:'画 JMM 交互图 + 口述 10 题', output:'JUC 学习起点清单' },
  { date:'2026-04-01', phase:'JUC', title:'synchronized 全链路', morning:'视频：尚硅谷 2025（synchronized、对象头、锁升级相关章节）', afternoon:'文档整理：基于 JavaGuide 并发入口整理 Mark Word/Monitor/锁升级 一页纸', evening:'模拟面试：拷打 synchronized 原理/锁升级过程/为什么不可降级，白板画锁升级图', output:'锁升级图 + 高频问答（10题）' },
  { date:'2026-04-02', phase:'JUC', title:'AQS 与 ReentrantLock', morning:'视频：黑马 2026 并发路线（AQS/ReentrantLock 章节）', afternoon:'文档整理：AQS state/CLH 队列/acquire-release 与公平锁 vs 非公平锁', evening:'模拟面试：AQS 追问（acquire 细节、park/unpark、公平性）+ 画 acquire 流程', output:'AQS 流程图 + ReentrantLock 对照表' },
  { date:'2026-04-03', phase:'JUC', title:'Condition 与并发协作', morning:'视频：尚硅谷 2025（Condition/并发工具类章节）', afternoon:'文档整理：Condition await/signal + CountDownLatch/CyclicBarrier/Semaphore 场景对比', evening:'模拟面试：并发协作题口述（至少 15 题），重点拷打使用场景和差异', output:'并发协作对比表 + 场景题清单' },
  { date:'2026-04-04', phase:'JUC', title:'线程池源码', morning:'视频：黑马 2026 并发路线（线程池参数与 execute 流程章节）', afternoon:'文档整理：7参数/拒绝策略/参数估算/监控指标，补充项目里的线程池配置依据', evening:'模拟面试：线程池高频拷打（参数、拒绝策略、Executors 坑点）+ 画 execute 流程图', output:'线程池配置模板 + execute 流程图' },
  { date:'2026-04-05', phase:'JUC', title:'CAS/原子类/并发容器', morning:'视频：尚硅谷 2025（CAS/ABA/原子类/并发容器章节）', afternoon:'文档整理：CAS与ABA、LongAdder、COW/BlockingQueue/CLQ 对照与适用场景', evening:'模拟面试：CAS 与容器拷打 + 手写生产者消费者（synchronized 版）', output:'CAS 与容器总结 + 生产者消费者代码' },
  { date:'2026-04-06', phase:'JUC', title:'JUC 综合收官', morning:'视频：黑马 2026 并发路线（ThreadLocal、并发收官章节）', afternoon:'文档整理：ThreadLocal 泄漏机制与最佳实践，并完成生产者消费者另外两种实现', evening:'模拟面试：JUC 全模块模拟（50 分钟）+ 复盘（70 分钟）', output:'JUC 模块定稿 + 弱项清单 v1' },
  { date:'2026-04-07', phase:'MOCK_INTERVIEW_2', title:'技术一面模拟', morning:'JavaSE + JVM 连续追问', afternoon:'逐题复盘，补齐薄弱点', evening:'重述薄弱题', output:'第二次模拟复盘 v1' },
  { date:'2026-04-08', phase:'MOCK_INTERVIEW_2', title:'技术二面模拟', morning:'JUC 深挖 + 手写题', afternoon:'模块串讲（JavaSE→JVM→JUC）', evening:'定稿"第二次模拟改进清单"', output:'第二次模拟复盘 v2' },
  { date:'2026-04-09', phase:'SPRING', title:'IOC 容器与 Bean 生命周期', morning:'视频：看课 1、2（手写Spring核心 + 核心组件解析）', afternoon:'createBean 全流程', evening:'画 Bean 生命周期图', output:'生命周期图' },
  { date:'2026-04-10', phase:'SPRING', title:'依赖注入与循环依赖', morning:'视频：看课 3、8（扫描流程 + Bean 生命周期源码）', afternoon:'三级缓存与循环依赖', evening:'默写 refresh() 主流程', output:'三级缓存时序图' },
  { date:'2026-04-11', phase:'SPRING', title:'AOP 源码', morning:'视频：看课 11、14（依赖注入 + 容器启动 refresh）', afternoon:'代理创建时机与失效场景', evening:'手写简易 AOP', output:'AOP 流程图 + 示例代码' },
  { date:'2026-04-12', phase:'SPRING', title:'事务与传播行为', morning:'视频：看课 17、18、25（BFPP + 配置类解析 + 循环依赖）', afternoon:'事务失效场景 + REQUIRED/REQUIRES_NEW/NESTED 实验', evening:'口述事务高频题', output:'事务失效清单' },
  { date:'2026-04-13', phase:'SPRING', title:'AOP 与事务底层', morning:'视频：看课 20、21（AOP + 事务底层）', afternoon:'梳理 AOP 代理创建时机与事务失效链路', evening:'画 AOP 代理 + 事务调用链两张图', output:'AOP/事务流程图' },
  { date:'2026-04-14', phase:'SPRING', title:'MVC 与 Boot 深入', morning:'视频：看课 26、28（Spring MVC + SpringBoot 源码）', afternoon:'自动配置与启动链路', evening:'画 MVC/Boot 两张图', output:'MVC/Boot 流程图' },
  { date:'2026-04-15', phase:'SPRING', title:'Spring 模块复盘', morning:'视频：看课 19、7（MyBatis 整合 + FactoryBean），有余力补看漏掉课程', afternoon:'模块问答 50 题', evening:'更新手册', output:'Spring 模块定稿' },
  { date:'2026-04-16', phase:'MQ_NETWORK_NETTY', title:'Kafka 核心架构', morning:'Topic/Partition/Group、ACK、幂等', afternoon:'消费位点与顺序消费', evening:'画 Kafka 架构图', output:'Kafka 架构图' },
  { date:'2026-04-17', phase:'MQ_NETWORK_NETTY', title:'Kafka 高性能 + RocketMQ', morning:'顺序写、页缓存、零拷贝、批处理', afternoon:'RocketMQ 事务消息/延迟消息', evening:'Kafka vs RocketMQ 对比', output:'中间件选型表' },
  { date:'2026-04-18', phase:'MQ_NETWORK_NETTY', title:'网络高频', morning:'TCP 三次握手/四次挥手/拥塞控制', afternoon:'HTTP1.1/2/3、HTTPS TLS 流程', evening:'URL 到页面全流程口述', output:'TCP/HTTPS 流程图' },
  { date:'2026-04-19', phase:'MQ_NETWORK_NETTY', title:'OS 与 IO 模型', morning:'进程线程协程、死锁、虚拟内存', afternoon:'select/poll/epoll、零拷贝、Reactor', evening:'画 epoll + Reactor 图', output:'IO 模型对比表' },
  { date:'2026-04-20', phase:'MQ_NETWORK_NETTY', title:'Netty 基础', morning:'线程模型、核心组件、Pipeline', afternoon:'粘包拆包、编解码、心跳', evening:'画 Netty 线程模型', output:'Netty 架构图' },
  { date:'2026-04-21', phase:'MQ_NETWORK_NETTY', title:'Netty 进阶', morning:'内存管理、零拷贝机制', afternoon:'手写简易 RPC 框架', evening:'复盘性能点', output:'RPC demo + 复盘' },
  { date:'2026-04-22', phase:'MQ_NETWORK_NETTY', title:'MQ/网络/OS/Netty 收官', morning:'模块串讲', afternoon:'MySQL 30题 + Redis 20题突击', evening:'更新手册', output:'本周模块定稿' },
  { date:'2026-04-23', phase:'MICROSERVICE', title:'分布式理论', morning:'CAP/BASE、一致性模型', afternoon:'Raft 选举与日志复制', evening:'画 Raft 图', output:'Raft 流程图' },
  { date:'2026-04-24', phase:'MICROSERVICE', title:'分布式锁与分布式事务', morning:'Redis/ZK/MySQL 锁对比', afternoon:'2PC/TCC/SAGA/本地消息表/Seata', evening:'输出选型模板', output:'锁与事务对比表' },
  { date:'2026-04-25', phase:'MICROSERVICE', title:'分布式实战题', morning:'雪花算法、时钟回拨', afternoon:'限流、幂等、一致性哈希', evening:'口述高频题', output:'分布式实战清单' },
  { date:'2026-04-26', phase:'MICROSERVICE', title:'微服务核心组件', morning:'Nacos 注册与配置', afternoon:'Feign、Gateway、负载均衡', evening:'画请求链路图', output:'微服务链路图' },
  { date:'2026-04-27', phase:'MICROSERVICE', title:'服务治理', morning:'Sentinel 熔断降级', afternoon:'灰度发布、服务治理、基础容器化', evening:'输出治理方案', output:'Sentinel 执行图' },
  { date:'2026-04-28', phase:'MICROSERVICE', title:'模式与框架映射', morning:'设计模式在 Spring/MyBatis/并发中的映射', afternoon:'模块综合串讲', evening:'更新面试手册', output:'模式映射表' },
  { date:'2026-04-29', phase:'MICROSERVICE', title:'分布式/微服务收官', morning:'全模块回顾', afternoon:'弱项攻坚', evening:'准备第三次模拟资料', output:'第三次模拟题库' },
  { date:'2026-04-30', phase:'MOCK_INTERVIEW_3', title:'三面模拟（架构与中间件）', morning:'Spring 深挖 + MyBatis', afternoon:'MQ + 分布式追问', evening:'复盘薄弱题', output:'第三次模拟复盘 v1' },
  { date:'2026-05-01', phase:'MOCK_INTERVIEW_3', title:'三面模拟（微服务与稳定性）', morning:'Gateway/Sentinel/服务治理追问', afternoon:'系统故障推演题', evening:'形成系统设计前置补强清单', output:'第三次模拟复盘 v2' },
  { date:'2026-05-02', phase:'SYSTEM_DESIGN', title:'方法论与容量估算', morning:'需求分析模板', afternoon:'容量/QPS/存储估算模板', evening:'形成答题模板', output:'系统设计答题框架' },
  { date:'2026-05-03', phase:'SYSTEM_DESIGN', title:'秒杀系统', morning:'流量入口、限流、风控', afternoon:'预扣库存、异步下单、一致性', evening:'10分钟口述', output:'秒杀方案图' },
  { date:'2026-05-04', phase:'SYSTEM_DESIGN', title:'短链 + 订单超时', morning:'短链编码/冲突/缓存', afternoon:'订单超时（延迟消息/时间轮/扫描）', evening:'对比方案优缺点', output:'短链与订单方案' },
  { date:'2026-05-05', phase:'SYSTEM_DESIGN', title:'Feed 流 + IM', morning:'推拉结合、收件箱模型', afternoon:'IM 投递可靠性与离线消息', evening:'口述演练', output:'Feed/IM 方案图' },
  { date:'2026-05-06', phase:'SYSTEM_DESIGN', title:'搜索与日志体系', morning:'ES 倒排、分片、副本', afternoon:'ELK、监控告警闭环', evening:'整理高频问答', output:'搜索与日志方案图' },
  { date:'2026-05-07', phase:'SYSTEM_DESIGN', title:'项目深挖与系统设计融合', morning:'把你的项目映射到系统设计框架', afternoon:'准备"从项目到架构"连续表达', evening:'录音复盘', output:'项目-系统设计融合稿' },
  { date:'2026-05-08', phase:'SYSTEM_DESIGN', title:'系统设计收官', morning:'6 道经典题快速过一遍', afternoon:'查漏补缺 + 手册定稿', evening:'准备第四次模拟', output:'系统设计终稿' },
  { date:'2026-05-09', phase:'MOCK_INTERVIEW_4', title:'最终一面', morning:'自我介绍 + 项目深挖', afternoon:'Java 基础/JVM/JUC/Spring 全链路', evening:'复盘并修正', output:'最终模拟复盘 v1' },
  { date:'2026-05-10', phase:'MOCK_INTERVIEW_4', title:'最终二面', morning:'MQ/分布式/微服务/系统设计', afternoon:'手撕算法 + HR 面', evening:'形成投递前终版资料', output:'最终模拟复盘 v2 + 投递资料包' }
];

// 构建日期→计划的索引
var PLAN_MAP = {};
PLAN_DATA.forEach(function(p) { PLAN_MAP[p.date] = p; });

// 所有计划日期列表（排序）
var PLAN_DATES = PLAN_DATA.map(function(p) { return p.date; });
